#!/bin/bash

set -x

########################################################################
## Prep the machine and get it updated
########################################################################
yum update -y
yum install -y curl git jq snap unzip
amazon-linux-extras install docker
service docker start
usermod -a -G docker ec2-user

curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
docker-compose version


# Install awscli 2.0. The image comes with 1.11.
pushd /tmp
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
unzip awscliv2.zip
rm /usr/bin/aws
ln -s /usr/local/bin/aws /usr/bin/aws
./aws/install
popd